### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by boazca** [sendgrid/java-http-client#10]
In The Client you use BasicResponseHandler to handle the response.
The problem is that when the status code is >= 300 HttpResponseException is thrown, ignoring the response body.
In Sendgrid v3 web API all the details of the failure are in the response body.
so when there is a failure, you have no information about what caused the problem.

You should either insert the response body to the exception message or return your Response even if the status code is >=300 (I think the second option is better).

**Comment by thinkingserious** [comment]
Thanks for the feedback @boazca!

This is on our roadmap and we appreciate your detailed feedback. I'll leave this ticket open to track when we implement this.

**Comment by thinkingserious** [comment]
@boazca,

This issue is resolved now: https://github.com/sendgrid/java-http-client/releases/tag/v2.3.3

Thanks again for the feedback!

I'll next be updating the dependency at sendgrid-java

**Comment by ifcwlme** [comment]
I think the problem haven't solved yet. 

I am trying to get error response message from Response object. But the api call throws IOException, which should happen only when there is network error.
![1](https://user-images.githubusercontent.com/1567613/48383635-8cfb0c00-e721-11e8-92b5-68b4629b7755.png)

For http response code 400, 401, 413 error, It should be handled by Response java object, instead of IOException.

![2](https://user-images.githubusercontent.com/1567613/48383636-8cfb0c00-e721-11e8-82f2-63de5e4bdf1d.png)

The relevant source code is in executeApiCall in com.sendgrid.Client.
![3](https://user-images.githubusercontent.com/1567613/48383637-8d93a280-e721-11e8-8083-1ffc038b1291.png)
