### ISSUE TITLE
Getting 'null' response from sendgrid API

### ISSUE THREAD

**Issue by romiSG** [sendgrid/java-http-client#140]
From our Project, through our Integration layer i.e. Oracle SOA/OSB, we are sending mail requests to be sent to customers using the API URL - 'https://api.sendgrid.com/v3/mail/send'.

Intermittently, we get 'null' in response after activating.

Every day there is almost 50+ cases which face this issue.

{{[http://xmlns.oracle.com/ServiceBusApplication/DistributeNotificationEBS/DistributeNotification}DistributeNotificationfault}](http://xmlns.oracle.com/ServiceBusApplication/DistributeNotificationEBS/DistributeNotification%7DDistributeNotificationfault%7D) messageType: {{[http://xmlns.oracle.com/ServiceBusApplication/DistributeNotificationEBS/DistributeNotification}Fault}](http://xmlns.oracle.com/ServiceBusApplication/DistributeNotificationEBS/DistributeNotification%7DFault%7D) parts: {{ Fault=} cause: {Client received SOAP Fault from server : null}

**Comment by JenniferMah** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).
